title: "A-Star Regulatory Solutions"
description: "Regulatory consulting for pharma, compliance, documentation, audits."
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  hard_wrap: false